version: '3.9'

services:
  # Collecte les données brutes
  collect-data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open_meteo-collect
    volumes:
      - ./data:/app/data
    environment:
      START_DATE: "2025-12-01"
      END_DATE: "2025-12-31"
    working_dir: /app
    entrypoint: python
    command: ["-m", "src.collect"]
    profiles:
      - collect

  # Consolide les données
  consolidate-data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open_meteo-consolidate
    volumes:
      - ./data:/app/data
    working_dir: /app
    entrypoint: python
    command: ["-m", "src.consolidate"]
    profiles:
      - consolidate
    depends_on:
      - collect-data

  # Crée les splits train/val/test
  split-data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open_meteo-split
    volumes:
      - ./data:/app/data
    working_dir: /app
    entrypoint: python
    command: ["-m", "src.split"]
    profiles:
      - split
    depends_on:
      - consolidate-data

  # Service ML (Jupyter pour exploration)
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open_meteo-jupyter
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    ports:
      - "8888:8888"
    working_dir: /app
    entrypoint: jupyter
    command: lab --ip=0.0.0.0 --allow-root --no-browser
    profiles:
      - jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
