# Compose de déploiement VPS pour Navettes Maritimes
# - API FastAPI sur api.<domaine>
# - Front Streamlit sur <domaine>
# - Réseau Traefik externe déjà présent sur le VPS

services:
  navettes-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navettes_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # - MODEL_PATH=${MODEL_PATH:-/model/model.pkl}
      - MODEL_PATH=/app/predict/api/src/model_v3.pkl  # Chemin absolu dans le conteneur
      - FEATURES_PATH=${FEATURES_PATH:-/model/features.json}
    # volumes:
    #   - maritime_artifacts:/model:ro
    expose:
      - "8000"
    # DIT À L'API OÙ SE TROUVE LE VRAI MAIN.PY
    command: uvicorn predict.api.src.main:app --host 0.0.0.0 --port 8000
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navettes-api.rule=Host(`api.navettes-maritimes.lab.zanza-creation.com`)"
      - "traefik.http.routers.navettes-api.entrypoints=websecure"
      - "traefik.http.routers.navettes-api.tls.certresolver=myresolver"
      - "traefik.http.services.navettes-api.loadbalancer.server.port=8000"

  front:
    build:
      context: .
      dockerfile: Dockerfile # utilise le même Dockerfile
    container_name: navettes_front
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      # - API_URL=${API_URL:-https://api.navettes-maritimes.lab.zanza-creation.com}
      - STREAMLIT_PORT=${STREAMLIT_PORT:-8501}
      # Le front appelle l'API directement par son nom de service Docker
      # sur le port 8000
      # force l'URL à pointer directement là où le POST est attendu
      - API_URL=http://navettes-api:8000/predict

    # On ajuste le chemin de l'app.py
    entrypoint: ["streamlit", "run", "predict/front/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    expose:
      - "8501"
    depends_on:
      - navettes-api
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navettes-front.rule=Host(`navettes-maritimes.lab.zanza-creation.com`)"
      - "traefik.http.routers.navettes-front.entrypoints=websecure"
      - "traefik.http.routers.navettes-front.tls.certresolver=myresolver"
      - "traefik.http.services.navettes-front.loadbalancer.server.port=8501"

volumes:
  maritime_artifacts:
    driver: local
    driver_opts:
      type: none
      device: ./data/artifacts
      o: bind

networks:
  traefik:
    external: true
